//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driving_School_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDENCE
    {
        public int ID { get; set; }
        public Nullable<int> STID { get; set; }
        public Nullable<System.DateTime> DATES { get; set; }
        public Nullable<System.TimeSpan> TIME_IN { get; set; }
        public Nullable<System.TimeSpan> TIME_OUT { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
