//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driving_School_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_DETAIL
    {
        public int ID { get; set; }
        public string CARNAME { get; set; }
        public string CARMODEL { get; set; }
        public string CARGEAR { get; set; }
        public string ENGINE_CC { get; set; }
        public Nullable<int> INSTRUCTOR_ID { get; set; }
    
        public virtual INSTRUCTOR INSTRUCTOR { get; set; }
    }
}
