//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driving_School_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DURATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DURATION()
        {
            this.STUDENTS = new HashSet<STUDENT>();
        }
    
        public int ID { get; set; }
        public string FULL_MONTH { get; set; }
        public string HALF_MONTH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT> STUDENTS { get; set; }
    }
}
