//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driving_School_Management_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DRIVING_SCHOOL_MANAGEMENT_SYSTEMEntities : DbContext
    {
        public DRIVING_SCHOOL_MANAGEMENT_SYSTEMEntities()
            : base("name=DRIVING_SCHOOL_MANAGEMENT_SYSTEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ATTENDENCE> ATTENDENCEs { get; set; }
        public virtual DbSet<DURATION> DURATIONs { get; set; }
        public virtual DbSet<SHIFT> SHIFTS { get; set; }
        public virtual DbSet<STUDENT> STUDENTS { get; set; }
    }
}
