//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driving_School_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int ID { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<int> TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public string SERVICE_DRIVER { get; set; }
        public string MESSAAGE { get; set; }
    }
}
